@extends('layouts.app')
@section('title','RED BAG — A Bag of Life')
@section('content')
<section class="hero"><div class="container hero-grid"><div class="hero-copy">
<span class="eyebrow">জাতি, ধর্ম ও দল নির্বিশেষে, রক্ত দিবো হাতে হাতে</span>
<h1>মানুষ মানুষের জন্য<br><span>এক ব্যাগ রক্ত,</span><br>এক জীবনের আলো।</h1>
<p>RED BAG একটি community-powered blood-help platform, যেখানে প্রয়োজনের মুহূর্তে রক্তদাতা ও রক্তপ্রার্থীর মধ্যে নিরাপদে যোগাযোগ তৈরি করা হয়।</p>
<div class="hero-actions"><a class="btn btn-primary btn-large" href="{{ route('blood.request') }}">রক্তের জন্য আবেদন করুন →</a><a class="btn btn-soft btn-large" href="{{ route('donor.register') }}">♥ &nbsp; আমি রক্ত দিতে চাই →</a></div>
<a class="emergency-card" href="{{ route('blood.request') }}"><span class="emergency-icon">!</span><span><strong>জরুরি রক্ত প্রয়োজন?</strong><small>জরুরি আবেদন করুন, কাছাকাছি রক্তদাতাদের কাছে পৌঁছে যান।</small></span><span class="arrow">→</span></a>
</div><div class="hero-visual"><div class="hero-glow"></div><div class="hero-quote">রক্ত দিয়ে<br>সহায়তার হাত<br>বাড়ান</div><div class="hand hand-top"></div><div class="hero-drop">♥</div><div class="hand hand-bottom"></div></div></div></section>
<section class="stats-strip"><div class="container stats-grid"><div><strong>২১০+</strong><span>নিবন্ধিত স্বেচ্ছাসেবক</span></div><div><strong>৮,৬০০+</strong><span>মানুষকে সহায়তা</span></div><div><strong>৬৪</strong><span>জেলায় আমাদের সাড়া</span></div><div><strong>১৩০+</strong><span>সফল রক্তদান</span></div><div><strong>অসংখ্য</strong><span>জীবনে আশার আলো</span></div></div></section>
<section class="section"><div class="container"><div class="section-heading"><span class="eyebrow">সহজ, দ্রুত, মানবিক</span><h2>RED BAG কীভাবে কাজ করে?</h2><p>মাত্র কয়েকটি ধাপে আপনার সাহায্য প্রয়োজনের মানুষের কাছে পৌঁছে যায়।</p></div><div class="steps-grid">
<article class="step-card"><div class="step-icon">01</div><h3>আবেদন করুন</h3><p>প্রয়োজনীয় রক্তের তথ্য দিয়ে সহজে আবেদন করুন।</p></article><div class="step-arrow">→</div>
<article class="step-card"><div class="step-icon">02</div><h3>রক্তদাতা খুঁজে পাওয়া</h3><p>কাছাকাছি উপযুক্ত রক্তদাতার কাছে request পৌঁছে যাবে।</p></article><div class="step-arrow">→</div>
<article class="step-card"><div class="step-icon">03</div><h3>যোগাযোগ স্থাপন</h3><p>সম্মতি ও যাচাইয়ের পর নিরাপদে যোগাযোগ তৈরি হবে।</p></article><div class="step-arrow">→</div>
<article class="step-card"><div class="step-icon">04</div><h3>জীবন বাঁচান</h3><p>রক্তদানের মাধ্যমে একটি পরিবারে আশার আলো ফিরিয়ে দিন।</p></article>
</div></div></section>
<section class="section section-muted"><div class="container story-grid"><div class="story-image"><div class="story-overlay">“প্রতি রক্তদাতা একজন জীবনরক্ষাকারী।”</div></div><div class="story-card"><span class="eyebrow">RED BAG DONOR</span><blockquote>“রক্তদান শুধু একটি চিকিৎসা সহায়তা নয়, এটি মানবতার প্রেমের উপহার।”</blockquote><div class="slider-dots"><span></span><span class="active"></span><span></span></div></div></div></section>
<section class="section"><div class="container coverage-grid"><div><div class="section-heading left"><span class="eyebrow">আমাদের নেটওয়ার্ক</span><h2>বাংলাদেশজুড়ে আমাদের দাতারা</h2><p>জেলা থেকে জেলা—মানুষ মানুষের পাশে দাঁড়ানোর একটি community network.</p></div><div class="coverage-list"><div><strong>৬৪</strong><span>জেলায় আমাদের সাড়া</span></div><div><strong>৮,৬০০+</strong><span>সফল সহায়তা</span></div><div><strong>১৩০+</strong><span>ভেরিফাইড রক্তদান</span></div><div><strong>২১০+</strong><span>নিবন্ধিত স্বেচ্ছাসেবক</span></div></div><a class="btn btn-primary" href="#">জেলা ভিত্তিক তথ্য দেখুন →</a></div><div class="map-card"><span>বাংলাদেশ</span><div class="map-dots">• • •<br>••••••<br> •••••<br>••••<br> •••</div></div></div></section>
<section class="section section-muted"><div class="container"><div class="section-heading left"><span class="eyebrow">কেন RED BAG?</span><h2>বিশ্বাস, গতি এবং মানবিকতা—এক জায়গায়</h2></div><div class="feature-grid"><article><b>♥</b><h3>সহজ ও দ্রুত আবেদন</h3><p>কম ধাপে জরুরি রক্তের request তৈরি করুন।</p></article><article><b>✓</b><h3>নিরাপদ ও যাচাইকৃত</h3><p>Donor ও request-এর privacy এবং verification গুরুত্ব পায়।</p></article><article><b>♟</b><h3>মানুষের পাশে মানুষ</h3><p>স্বেচ্ছাসেবক ও community network দ্রুত সমন্বয় করে।</p></article><article><b>▥</b><h3>স্বচ্ছ ও পরিমাপযোগ্য</h3><p>Donation history ও impact data সহজে দেখা যায়।</p></article></div></div></section>
<section class="cta-band"><div class="container cta-inner"><div><span class="eyebrow">একটি ছোট সিদ্ধান্ত</span><h2>আপনার রক্ত অন্য কারো<br>নতুন জীবনের সূচনা হতে পারে।</h2><p>আজই RED BAG-এর সঙ্গে যুক্ত হোন এবং মানবতার পাশে দাঁড়ান।</p></div><a class="btn btn-white btn-large" href="{{ route('donor.register') }}">এখনই রক্ত দিতে চাই →</a></div></section>
<section class="section"><div class="container"><div class="section-heading row-heading"><div><span class="eyebrow">সাম্প্রতিক রক্তের আবেদন</span><h2>কেউ একজন এখন আপনার সাহায্য চাইছে</h2></div><a href="{{ route('blood.request') }}">সব আবেদন দেখুন →</a></div><div class="request-grid">@foreach([['B+','ঢাকা','Square Hospital, ঢাকা','২ ব্যাগ'],['A+','গুলশান','Labaid Hospital, ঢাকা','১ ব্যাগ'],['O+','ঢাকা','Dhaka Medical College','৩ ব্যাগ'],['AB-','রাজশাহী','Evercare Hospital','১ ব্যাগ']] as $request)<article class="request-card"><div class="blood-badge">{{ $request[0] }}</div><span class="urgency">জরুরি</span><h3>{{ $request[3] }}</h3><p>{{ $request[2] }}</p><small>{{ $request[1] }}</small><a class="btn btn-primary btn-full" href="{{ route('blood.request') }}">সহায়তা করতে চাই</a></article>@endforeach</div></div></section>
<section class="section section-muted"><div class="container faq-grid"><div><div class="section-heading left"><span class="eyebrow">সচরাচর জিজ্ঞাসা</span><h2>আপনার প্রশ্নের উত্তর</h2></div><details open><summary>রক্ত দিতে হলে কি কি প্রয়োজন?</summary><p>নিরাপদ রক্তদানের আগে সংশ্লিষ্ট চিকিৎসা/রক্তদান কেন্দ্রের screening ও eligibility নির্দেশনা অনুসরণ করতে হবে।</p></details><details><summary>কত দিন পর আবার রক্ত দিতে পারি?</summary><p>এটি donor-এর স্বাস্থ্য ও স্থানীয় medical guidance-এর উপর নির্ভর করে।</p></details><details><summary>আবেদনের পর কত সময়ে রক্তদাতা পাওয়া যায়?</summary><p>Location, blood group, urgency এবং available donor-এর উপর সময় পরিবর্তিত হয়।</p></details><details><summary>রক্তদাতার সঙ্গে যোগাযোগ কীভাবে হয়?</summary><p>Consent ও প্রয়োজনীয় verification-এর পর RED BAG নিরাপদভাবে connection তৈরি করে।</p></details></div><div class="faq-callout"><div class="big-heart">♥</div><h3>রক্ত দিতে পারবেন?</h3><p>আপনার কয়েক মিনিট একজন মানুষের জীবন বাঁচাতে পারে।</p><a class="btn btn-primary" href="{{ route('donor.register') }}">আমি রক্ত দিতে চাই →</a></div></div></section>
@endsection